config/routes.rb
Mcp::Application.routes.draw do

  get "workers/scrape_plates"

  get 'plates/scraper'
  
  get "tickets/index"

  get "tickets/new"

  get "tickets/destroy"

  get "plates/index"
  
  root to: 'pages#home'

  get   'pages/about'
  match 'contact', to: 'pages#contact'
  get   'pages/contact'



  resources :tickets
  resources :plates
  resources :users
  resources :sessions


  match '/signup',   to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete


  


  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }
	validates :password_confirmation, presence: true
	attr_accessible :name, :email, :password, :password_confirmation
	before_save { |user| user.email = user.email.downcase }
  	before_save :create_remember_token
	
	has_many :authorizations
	has_many :usersplates
  	has_many :plates, :through => :usersplates

	private

	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end
end




 
  
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :edit, :update, :destroy,]
  
  before_filter :correct_user,  only: [:edit, :update, :show]



  def index
  	@users=User.all 
  end

  def show
  	@user=User.find(params[:id])
    @plate = Plate.new
  end

  def new
  	@user=User.new	
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to MCP!"
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to users_path
  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Citation Number</th>
      <th>License Plate</th>
      <th>Date</th>
      <th>Price</th>
      <th>Fee</th>
      <th>Total</th>
    </tr>
  </thead>
<% current_user.plates.each do |plate| %>
  <% plate.tickets.each do |ticket| %>
  <tbody>
    <tr>
      <td><%= ticket.citation_number%></td>
      <td><%= ticket.plate.license  %></td>
      <td><%= ticket.date.strftime("%m/%d/%y") %></td>
      <td>$<%= ticket.price %></td>
      <td>$<%= ticket.fee %></td>
      <td>$<%= ticket.price + ticket.fee %></td>
    </tr>
  </tbody> 
    <% end %>
<% end %>

app/views/users/edit.html.erb
 <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "update" %>
    <% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= @users %>

app/views/users/new.html.erb
<%= form_for(@user, html: { class: "form-signin"}) do |f| %>
	<%= render 'shared/error_messages', object: @user %>
	<h2 class="form-signin-heading">Sign Up</h2>
	<div class="control-group">
		<%= f.label :name, class: 'control-label' %>
		<div class="controls">
			<%= f.text_field :name %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :email, class: 'control-label' %>
		<div class="controls">
			<%= f.text_field :email %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :password, class: 'control-label' %>
		<div class="controls">
			<%= f.password_field :password %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :password_confirmation, "Confirmation", class: 'control-label' %>
		<div class="controls">
			<%= f.password_field :password_confirmation %>
		</div>
	</div>
	<div class="control-group" >
		<div class="controls">
	  <%= f.submit 'Sign Up!', class: 'btn btn-primary'%>
	</div>
<% end %>

app/views/users/show.html.erb
<div class="row-fluid">
  <div class="span6">
  	<h2>Your Info</h2>
	<p><%= @user.name %></p>
	<p><%= @user.email %></p>
	<p><%= link_to "Update", edit_user_path(current_user), class: "btn btn-primary" %></p>
  </div>
  <div class="span6">
  	<h2>Your Plates</h2>
  	<div id="plates"><% current_user.plates.each do |plate| %>
  		<div class="plate">
  			<%= plate.license.upcase %>
  		</div>
  		<div>
        <%= link_to "Delete", plate, method: "delete", 
            class: "btn btn-mini" %>
        <%= link_to "Check tickets", plates_scraper_path(plate_id: plate), 
            class: "btn btn-mini" %>
        </div>
  		<% end %>
  	</div>
  <%= form_for(@plate) do |f| %>
	<div class="control-group">
		<%= f.label :Add_plate, class: 'control-label' %>
		<div class="controls">
			<%= f.text_field :license, :placeholder => "Format: 373mzf" %>
		</div>
	</div>
	<div class="control-group" >
    	<div class="controls">
      <%= f.submit 'Add', class: 'btn btn-primary'%>
    </div>
  </div>
  <% end %>
  </div>
</div>
<div class='row-fluid'>
  <div class="tickets">    
    <h2>Your Tickets</h2>
  </div>
    <div class='pay-link'><a href="https://step1.caledoncard.com/citations/milwaukee.html">Pay Tickets</a>
    </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Citation Number</th>
            <th>License Plate</th>
            <th>Date</th>
            <th>Price</th>
            <th>Fee</th>
            <th>Total</th>
          </tr>
        </thead>
      <% current_user.plates.each do |plate| %>
        <% plate.tickets.each do |ticket| %>
        <% if ticket.paid == false%>
        <tbody>
          <tr>
            <td><%= ticket.citation_number%></td>
            <td><%= ticket.plate.license.upcase  %></td>
            <td><%= ticket.date.strftime("%m/%d/%y") %></td>
            <td>$<%= ticket.price %></td>
            <td>$<%= ticket.fee %></td>
            <td>$<%= ticket.price + ticket.fee %></td>
          </tr>
        </tbody>
        <% end %> 
        <% end %>
      <% end %>  
      </table> 
  </div>
</div>




 

  

  	