config/routes.rb
Mcp::Application.routes.draw do

  get "workers/scrape_plates"

  get 'plates/scraper'
  
  get "tickets/index"

  get "tickets/new"

  get "tickets/destroy"

  get "plates/index"
  
  root to: 'pages#home'

  get   'pages/about'
  match 'contact', to: 'pages#contact'
  get   'pages/contact'



  resources :tickets
  resources :plates
  resources :users
  resources :sessions


  match '/signup',   to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete


  


  

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "MCP", root_url, id: 'logo' %>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li><%= link_to 'Home', root_url %></li>
          <li><%= link_to 'About', pages_about_path %></li>
          <% if current_user.present? %>
          <li><%= link_to 'Profile', current_user, class: "active" %></li>
          <li><%= link_to 'Sign Out', signout_path, method: 'delete', class: "active" %></li>
          <% else %>
          <li><%= link_to 'Sign In',signin_path, class: "active"%></li>   
      <% end %> 
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>MCP</title>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    'application', media: "all" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">

      <%= yield %>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>